
name: Test and Package

on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
        poetry config virtualenvs.create false  # Ensure Poetry uses the project environment
        poetry --version

    - name: Install dependencies with Poetry
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry install --no-root  # Install all dependencies without installing the root package

    - name: Run tests
      run: pytest tests

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/